version: "3"

services:
  webapi:
    build: .
    ports:
      - "8080:8080"

    networks:
      - scrub-network

    depends_on:
      - db

  db:
    image: postgres
    restart: always

    environment:
      postgres_password: example
    volumes:
      - dbdata-scrub:/var/lib/postgresql/data

volumes:
  dbdata-scrub:

networks:
  scrub-network:
    driver: bridge
