version: "3"

services:
  webapi:
    build: .
    ports:
      - "8080:8080"

    networks:
      - scrub-network

    depends_on:
      - db

  db:
    image: postgres
    restart: always

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: db
    volumes:
      - dbdata-scrub:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    networks:
      - scrub-network

volumes:
  dbdata-scrub:

networks:
  scrub-network:
    driver: bridge
